### ISSUE TITLE
Access img ref/reference

### ISSUE THREAD

**Issue by darkowic** [nitin42/react-imgpro#20]
Hello!

I need to access reference of the rendered img component. It is impossible right now.

We have 2 options:
* Add new prop `innerRef`/`imgRef`/etc which will be passed to img component
* Use React 16 `forwardRef` API to pass `ref` to the rendered img component

What do you think? Since this component is rendering `img` component directly, I think the second solution will be more appropriate.

**Comment by nitin42** [comment]
Seems doable! Thanks for the suggestion. Can you create a pull request for this ? @Sunshine168 this is interesting, what do you think ?

**Comment by Sunshine168** [comment]
Absolutely, ref is useful, and recommend to use forwardRef Api.

**Comment by Sunshine168** [comment]
BTW forwardRef Api is available in React 16.3

**Comment by Sunshine168** [comment]
@darkowic  Did you like to create a PR about this feat ~  or  I will work on this .

**Comment by Sunshine168** [comment]
@LukasDrgon  Grateful~ I just make sure you take it

**Comment by Sunshine168** [comment]
Hi any news about this ~

**Comment by Sunshine168** [comment]
Done #29
