### ISSUE TITLE
Not working on react-native

### ISSUE THREAD

**Issue by CoderHuzaifa** [nitin42/react-imgpro#23]
package.json :   
 "react": "16.3.1",
    "react-imgpro": "^1.3.9",
    "react-native": "0.55.4",

I am getting the following error when trying to import this library:

**A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`**

**Comment by Sunshine168** [comment]
This lib did not support react-native

**Comment by CoderHuzaifa** [comment]
Close #123
