### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ghoshnirmalya** [nitin42/react-imgpro#25]
Version: 1.3.9
NPM version: 6.2.0
Node version: 10.8.0

I'm getting this error while using this plugins with Next.js.

**Comment by Sunshine168** [comment]
I will investigate soon

**Comment by Sunshine168** [comment]
1.3.10 had been released  pls update to the latest version

**Comment by Sunshine168** [comment]
https://github.com/nitin42/react-imgpro/pull/26

**Comment by ghoshnirmalya** [comment]
I'm getting `Error: Cannot find module './build/main.js'` on 1.3.10.
