### ISSUE TITLE
Module not found: Can't resolve './build/main.js' in 

### ISSUE THREAD

**Issue by Asinox** [nitin42/react-imgpro#27]
Hello there, After npm install --save react-imgpro i got 

`Module not found: Can't resolve './build/main.js' in  '.../node_modules/react-imgpro'
`
Thanks!

**Comment by Sunshine168** [comment]
Sorry about this , i make a mistake  when publishing this lib. I will fix soon

**Comment by Sunshine168** [comment]
Pls try install the latest version
